name: 'Get Mathlib with cache'
description: 'Creates a working copy of Mathlib4 and its cache'
runs:
  using: "composite"
  steps:

    - name: Download_Mathlib4
      uses: actions/checkout@v4
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: 'leanprover-community/mathlib4'
        # The branch, tag or SHA to checkout. When checking out the repository that
        # triggered a workflow, this defaults to the reference or SHA for that event.
        # Otherwise, uses the default branch.
        #ref: ''
        # Number of commits to fetch. 0 indicates all history for all branches and tags.
        # Default: 1
        #fetch-depth: 0

    - name: install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: cleanup
      shell: bash
      run: |
        find . -name . -o -prune -exec rm -rf -- {} +
        # Delete all but the 5 most recent toolchains.
        # Make sure to delete both the `~/.elan/toolchains/X` directory and the `~/.elan/update-hashes/X` file.
        # Skip symbolic links (`-type d`), the current directory (`! -name .`), and `nightly` and `stable`.
        if cd ~/.elan/toolchains && find . -maxdepth 1 -type d ! -name . -print0 | xargs -0 ls -1td | grep -v 'nightly$' | grep -v 'stable$' | tail -n +6 | xargs -I {} sh -c 'echo {} && rm -rf "{}" && rm "../update-hashes/{}"'; then
            : # Do nothing on success
        else
            : # Do nothing on failure, but suppress errors
        fi

    # The Hoskinson runners may not have jq installed, so do that now.
    - name: 'Setup jq'
      uses: dcarbone/install-jq-action@v1.0.1


    - name: install elan
      shell: bash
      run: |
        set -o pipefail
        curl -sSfL https://github.com/leanprover/elan/releases/download/v3.0.0/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
        ./elan-init -y --default-toolchain none
        echo "$HOME/.elan/bin" >> "${GITHUB_PATH}"
        elan


    - name: list
      shell: bash
      run: ls
